### ISSUE TITLE
Fails with unique index.

### ISSUE THREAD

**Issue by matthewlilley** [spatie/eloquent-sortable#44]
Hey guys,

I'm unsure if this is intentional, but I added this to a project that uses unique indexes on the order column, and it caused this package to fail because of that. I removed the unique index and it works perfectly.

**Comment by danhunsaker** [comment]
When re-sorting a column, it takes extra care to do it in a way that keeps every value entirely unique the entire transaction, and generally several extra steps. It's doable, but the current implementation doesn't consider that approach, partly (I would guess) because of the added complexity.

Removing the `unique` constraint is the correct approach for now. I can't say whether supporting `unique` sort columns is something Spatie wants to do, but unless/until they do, that's your best bet. (The package itself enforces uniqueness anyway, so it's not generally going to cause issues as is.)

**Comment by freekmurze** [comment]
> When re-sorting a column, it takes extra care to do it in a way that keeps every value entirely unique the entire transaction, and generally several extra steps. It's doable, but the current implementation doesn't consider that approach, partly (I would guess) because of the added complexity.

Yeah, when creating this package it didn't consider `unique` columns. If the code to achieve this is simple, I'd accept a fully tested, non breaking PR that adds support for transactions. It should work for at least `sqlite` and `mysql`.

**Comment by matthewlilley** [comment]
Just thought I'd mention it, wasn't a big deal pulling the unique index for this project, but ideally it should take that into account as it's a pretty common use. If I find some time, I'll fill a PR.

**Comment by freekmurze** [comment]
Sound good, don't feel yourself obligated in any way.

**Comment by markwalet** [comment]
This issue sounds 'closable'
