### ISSUE TITLE
Why there are no methods for moving after/before?

### ISSUE THREAD

**Issue by zvermafia** [spatie/eloquent-sortable#62]
I want to move an item after/before another item. Not to one position up/down, to the start/end or swapping positions.

**Comment by freekmurze** [comment]
There are no methods for this because not many people needs this functionality. It could also leas do to a lot of queries being executed.

Do this is your own project.

**Comment by jBOKA** [comment]
I came across this because of https://github.com/Naxon/nova-field-sortable/issues/20

In my opinion a `moveBefore` and `moveAfter` makes sense in exactly the same way as 'moveToStart' and `moveToEnd` makes sense. It would only results in a different where clause when incrementing the sort_order of all the other affected model instances. It's basically just a generalization of moveToStart with a different starting point.

@freekmurze If you reconsider, I'd try to create pull request without queries that are more costly than `moveToStart`. This is at least more efficient then setting all ids and covers most use cases in terms of UI-driven manual reordering (e.g. drag and drop).
